# Generated by Django 3.0.2 on 2020-03-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='name', max_length=250),
        ),
        migrations.AddField(
            model_name='game',
            name='numPlayers',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(default='pub', max_length=250),
        ),
    ]
