# Generated by Django 3.0.2 on 2020-03-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200318_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='publisher',
        ),
    ]
