# Generated by Django 3.0.2 on 2020-03-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_game_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='numPlayers',
            field=models.IntegerField(verbose_name='Number of Players'),
        ),
    ]
