# Generated by Django 3.0.2 on 2020-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200318_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stores',
            field=models.ManyToManyField(to='main_app.Store'),
        ),
    ]
